---

- hosts: web_servers
  become: true
  tasks:

  - name: update repo index & install apache2 and php packages
    tags: web
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: push index html file to webserver
    tags: web
    copy:
      src: site_template.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

