- name: update repo index & install apache2 and php packages
  tags: web
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: start & enable  apache
  tags: web
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: change loglevel to warn
  tags: web
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^LogLevel'
    line: LogLevel warn
  when: ansible_distribution == "Ubuntu"
  register: conf

- name: restart apaceh2 service if conf changed
  tags: web
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: conf.changed

- name: push index html file to webserver
  tags: web
  copy:
    src: site_template.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
